apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecommerce-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/ecommerce-frontend:latest
        ports:
        - containerPort: 3000
