name: Terraform CI/CD Foundation

on:
  push:
    branches:
      - main
      - 05-external-dns
  pull_request:
    branches:
      - main
      - 05-external-dns
  workflow_dispatch:

env:
  # env variable name can only have _ and not -
  ENV_S3_NAME: "grp-3joseph03-s3"                  # "grp-3${local.name_prefix}s3"
  ENV_DYNAMODB_NAME: "grp-3joseph03-dynamodb"      # "grp-3${local.name_prefix}dynamodb"

# remember to use different names for tfplan file in different stages
# cancel job may cause state lock
# aws dynamodb delete-item \
#  --table-name grp-3joseph03-dynamodb \
#  --key '{"LockID":{"S":"grp-3joseph03-cap-eks-tfstate/cap-eks/terraform.tfstate"}}'
jobs:
  eks-cluster-dns-ingress:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Check Terraform Format
        run: terraform fmt -check -recursive

      - name: Check Terraform Format (bootstrap-s3)
        working-directory: ./bootstrap-s3
        run: terraform fmt -check -recursive

#================== bootstrap-s3 ==================
      - name: Terraform Init (bootstrap-s3)
        working-directory: ./bootstrap-s3
        run: terraform init

      - name: Validate Terraform (bootstrap-s3)
        working-directory: ./bootstrap-s3
        run: terraform validate

      - name: Check S3 bucket existence
        id: check_s3
        run: |
          if aws s3api head-bucket --bucket "${ENV_S3_NAME}" 2>/dev/null; then
            echo "s3_exists=true" >> $GITHUB_OUTPUT
          else
            echo "s3_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Plan (bootstrap-s3)
        working-directory: ./bootstrap-s3
        if: steps.check_s3.outputs.s3_exists == 'false' 
        run: terraform plan -out=tfplan-s3 -var="s3_name=${ENV_S3_NAME}"

      - name: Terraform Apply (bootstrap-s3)
        working-directory: ./bootstrap-s3
        if: steps.check_s3.outputs.s3_exists == 'false' 
        run: terraform apply tfplan-s3

#==================== bootstrap-dynamodb ==================
      - name: Terraform Init (bootstrap-dynamodb)
        working-directory: ./bootstrap-dynamodb
        run: terraform init

      - name: Validate Terraform (bootstrap-dynamodb)
        working-directory: ./bootstrap-dynamodb
        run: terraform validate

      - name: Check DynamoDB table existence
        id: check_dynamodb
        run: |
          if aws dynamodb describe-table --table-name "${ENV_DYNAMODB_NAME}" 2>/dev/null; then
            echo "dynamodb_exists=true" >> $GITHUB_OUTPUT
          else
            echo "dynamodb_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Plan (bootstrap-dynamodb)
        working-directory: ./bootstrap-dynamodb
        if: steps.check_dynamodb.outputs.dynamodb_exists == 'false' 
        run: terraform plan -out=tfplan-dyn -var="dynamodb_name=${ENV_DYNAMODB_NAME}"

      - name: Terraform Apply (bootstrap-dynamodb)
        working-directory: ./bootstrap-dynamodb
        if: steps.check_dynamodb.outputs.dynamodb_exists == 'false' 
        run: terraform apply tfplan-dyn

#================== vpc & eks ==================
      - name: Terraform Init (root)
        run: terraform init

      - name: Validate Terraform (root)
        run: terraform validate
        
      - name: Terraform Plan with Target (VPC & EKS)
        run: |
          terraform plan -out=tfplan-vpc-eks -target=module.vpc -target=module.eks \
            -lock=false 
            #-var="domain_name=sctp-sandbox.com"   # error if there is space "- var"
            # -var is not required because domain_name is defined in terraform.tfvars
            # "domain_name is required by module.external_dns in workflow

      - name: Terraform Apply Targeted Plan
        run: terraform apply tfplan-vpc-eks

#================== ingress, externa-dns, namespaces =================
      - name: Terraform Full Plan
        id: full_plan
        run: terraform plan -out=tfplan-full

      - name: Terraform Apply Full Plan
        run: terraform apply tfplan-full

      - name: Show Full Plan
        id: show_plan
        run: terraform show -no-color tfplan-full > plan_output.txt

      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message-path: plan_output.txt
