name: Auto PR to uat

on:
  push:
    branches-ignore:
      - main
      - uat
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This fetches all history and branches

      - name: Create PR to uat
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}  # Explicitly set source branch
          destination_branch: uat
          pr_title: "Auto PR to uat from ${{ github.ref_name }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}