name: Auto PR to main

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR to main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_title: "Auto PR to main from uat"
          github_token: ${{ secrets.GITHUB_TOKEN }}
